services:
  - type: web
    name: AgentHelp
    env: python
    runtime: python
    pythonVersion: 3.9.18
    buildCommand: |
      apt-get update && apt-get install -y gcc python3-dev libffi-dev
      pip install -r requirements.txt
    startCommand: python aviahelp_bot.py
    plan: free
