services:
  - type:  web
    name: agenthelpbot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python aviahelp_bot.py
    runtime: python
    pythonVersion: 3.10.13
