services:
  - type: web
    name: AgentHelp
    runtime: python
    pythonVersion: 3.10.13
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python aviahelp_bot.py"
    plan: free
